// <auto-generated />
using System;
using FolderDiag.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolderDiag.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview");

        modelBuilder.Entity("FolderDiag.Data.Entities.FileIndexEntity", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("Created").HasColumnType("TEXT");
            b.Property<string>("Extension").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<string>("FullPath").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<bool>("IsDirectory").HasColumnType("INTEGER");
            b.Property<DateTime>("LastModified").HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasMaxLength(260).HasColumnType("TEXT");
            b.Property<int>("ScanHistoryId").HasColumnType("INTEGER");
            b.Property<long>("Size").HasColumnType("INTEGER");
            b.Property<long>("TotalSize").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("Extension");
            b.HasIndex("LastModified");
            b.HasIndex("Name");
            b.HasIndex("Size");
            b.HasIndex("ScanHistoryId", "IsDirectory");
            b.ToTable("FileIndex");
        });

        modelBuilder.Entity("FolderDiag.Data.Entities.ScanHistoryEntity", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("ErrorMessage").HasColumnType("TEXT");
            b.Property<bool>("IsComplete").HasColumnType("INTEGER");
            b.Property<string>("RootPath").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<double>("ScanDurationSeconds").HasColumnType("REAL");
            b.Property<DateTime>("ScanTime").HasColumnType("TEXT");
            b.Property<int>("TotalFiles").HasColumnType("INTEGER");
            b.Property<int>("TotalFolders").HasColumnType("INTEGER");
            b.Property<long>("TotalSize").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("RootPath");
            b.HasIndex("ScanTime");
            b.ToTable("ScanHistory");
        });

        modelBuilder.Entity("FolderDiag.Data.Entities.SettingEntity", b =>
        {
            b.Property<string>("Key").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Value").IsRequired().HasColumnType("TEXT");
            b.HasKey("Key");
            b.ToTable("Settings");
        });

        modelBuilder.Entity("FolderDiag.Data.Entities.FileIndexEntity", b =>
        {
            b.HasOne("FolderDiag.Data.Entities.ScanHistoryEntity", "ScanHistory")
             .WithMany()
             .HasForeignKey("ScanHistoryId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
